// @vitest-environment happy-dom
import axe from 'axe-core'
import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { ArticleSummary, LibraryState } from '../src/api/generated/models'
import type { ServerApi as Api } from '../src/api/server-api'
import LibraryView from '../src/features/library/LibraryView.vue'

function item(id:string,state:Partial<LibraryState>):ArticleSummary{return{id,sourceId:'source-1',canonicalUrl:`https://example.com/${id}`,title:id,author:'Reporter',publishedAt:'2026-08-14T10:00:00Z',fetchedAt:'2026-08-14T10:01:00Z',excerpt:'Excerpt',contentPermission:'metadata_only',language:'en',topics:[],library:{articleId:id,readAt:null,savedAt:null,hiddenAt:null,...state},ranking:{score:.5,algorithmVersion:'v1',calculatedAt:'2026-08-14T10:02:00Z',contributions:[]}}}
function fakeApi(){const records=[item('saved-story',{savedAt:'2026-08-14T11:00:00Z'}),item('read-story',{readAt:'2026-08-14T11:00:00Z'}),item('unread-story',{}),item('hidden-story',{hiddenAt:'2026-08-14T11:00:00Z'})];const feed=vi.fn(async query=>({items:records.filter(article=>query.includeHidden?true:!article.library.hiddenAt).filter(article=>query.saved?article.library.savedAt:true).filter(article=>query.read===undefined?true:Boolean(article.library.readAt)===query.read),nextCursor:null}));const updateLibrary=vi.fn(async(id,patch)=>{const article=records.find(value=>value.id===id)!;article.library={...article.library,readAt:patch.read===undefined?article.library.readAt:patch.read?'2026-08-14T12:00:00Z':null,savedAt:patch.saved===undefined?article.library.savedAt:patch.saved?'2026-08-14T12:00:00Z':null,hiddenAt:patch.hidden===undefined?article.library.hiddenAt:patch.hidden?'2026-08-14T12:00:00Z':null};return article.library});return{feed,sources:vi.fn(async()=>({items:[{id:'source-1',name:'Local source',url:'https://example.com/feed',kind:'feed',enabled:true,contentPermission:'metadata_only',adapterConfig:{format:'rss'},scraperPolicy:{status:'not_applicable',termsUrl:null,robotsUrl:null,reviewedAt:null,reviewNotes:null},credentialConfigured:false,lastSuccessAt:null,lastError:null,retryAfter:null}]})),updateLibrary} as unknown as Api}

beforeEach(()=>localStorage.clear())
describe('personal library',()=>{
  it('loads authoritative saved/read/unread/hidden views and restores hidden articles',async()=>{const api=fakeApi(),wrapper=mount(LibraryView,{props:{serverApi:api},attachTo:document.body});await flushPromises();expect(wrapper.text()).toContain('saved-story');expect(wrapper.text()).not.toContain('read-story');await wrapper.findAll('button').find(button=>button.text()==='Unread')!.trigger('click');await flushPromises();expect(wrapper.text()).toContain('unread-story');await wrapper.findAll('button').find(button=>button.text()==='Read')!.trigger('click');await flushPromises();expect(wrapper.text()).toContain('read-story');await wrapper.findAll('button').find(button=>button.text()==='Hidden')!.trigger('click');await flushPromises();expect(wrapper.text()).toContain('hidden-story');await wrapper.findAll('button').find(button=>button.text()==='Restore')!.trigger('click');await flushPromises();expect(api.updateLibrary).toHaveBeenCalledWith('hidden-story',{hidden:false},expect.any(AbortSignal));expect(wrapper.text()).not.toContain('hidden-story');expect((await axe.run(wrapper.element)).violations).toEqual([]);wrapper.unmount()})
  it('persists only the disposable selected view and reloads authoritative records',async()=>{const api=fakeApi(),first=mount(LibraryView,{props:{serverApi:api}});await flushPromises();await first.findAll('button').find(button=>button.text()==='Unread')!.trigger('click');await flushPromises();first.unmount();expect({...localStorage}).toEqual({'news-aggregator:library-view':'unread'});const second=mount(LibraryView,{props:{serverApi:api}});await flushPromises();expect(second.get('button[aria-pressed=true]').text()).toBe('Unread');expect(api.feed).toHaveBeenLastCalledWith(expect.objectContaining({read:false}),expect.any(AbortSignal));second.unmount()})
  it('shows useful empty and retryable error states',async()=>{const api=fakeApi();vi.mocked(api.feed).mockResolvedValueOnce({items:[],nextCursor:null});const empty=mount(LibraryView,{props:{serverApi:api}});await flushPromises();expect(empty.text()).toContain('No saved articles');empty.unmount();vi.mocked(api.feed).mockRejectedValueOnce(new TypeError('offline'));const failed=mount(LibraryView,{props:{serverApi:api}});await flushPromises();expect(failed.get('[role=alert]').text()).toContain('temporarily unavailable');expect(failed.text()).toContain('Try again');failed.unmount()})
  it('keeps a hidden article recoverable when restore fails',async()=>{localStorage.setItem('news-aggregator:library-view','hidden');const api=fakeApi();vi.mocked(api.updateLibrary).mockRejectedValueOnce(new TypeError('offline'));const wrapper=mount(LibraryView,{props:{serverApi:api}});await flushPromises();await wrapper.findAll('button').find(button=>button.text()==='Restore')!.trigger('click');await flushPromises();expect(wrapper.text()).toContain('hidden-story');expect(wrapper.text()).toContain('temporarily unavailable');wrapper.unmount()})
  it.each([['saved',{saved:true}],['unread',{read:false}],['read',{read:true}]] as const)('follows every cursor for the %s view',async(view,filter)=>{localStorage.setItem('news-aggregator:library-view',view);const api=fakeApi();vi.mocked(api.feed).mockResolvedValueOnce({items:[item(`${view}-page-one`,{})],nextCursor:`${view}-cursor`}).mockResolvedValueOnce({items:[item(`${view}-page-two`,{})],nextCursor:null});const wrapper=mount(LibraryView,{props:{serverApi:api}});await flushPromises();expect(wrapper.text()).toContain(`${view}-page-one`);expect(wrapper.text()).toContain(`${view}-page-two`);expect(api.feed).toHaveBeenNthCalledWith(2,expect.objectContaining({...filter,cursor:`${view}-cursor`}),expect.any(AbortSignal));wrapper.unmount()})
})
